version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8866:8000"
    depends_on:
      - redis
    volumes:
      - .:/vocode_project
      - /etc/letsencrypt:/etc/letsencrypt:ro  # for SSL
    command: uvicorn app.web.server:app --host 0.0.0.0 --port 8000 --reload --ssl-keyfile /etc/letsencrypt/live/mellettan.ru/privkey.pem --ssl-certfile /etc/letsencrypt/live/mellettan.ru/fullchain.pem

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
